workflows:
  android-release:
    name: Android Release SDK34
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      java: 17
      vars:
        ANDROID_COMPILE_SDK_VERSION: "34"
        ANDROID_TARGET_SDK_VERSION: "34"
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
