name: "stock_manager" 
description: "Beautiful Stock Manager"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  intl: ^0.20.3
  fl_chart: ^0.68.0 # for beautiful charts
  google_fonts: ^6.2.1
  sqflite: ^2.4.3
  shared_preferences: 2.5.5
  sqflite_common_ffi_web: ^1.1.2
  csv: ^8.0.0
  share_plus: ^13.3.0
  path_provider: ^2.1.6

flutter:
  uses-material-design: true