name: "stock_manager" 
description: "Beautiful Stock Manager"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  intl: ^0.19.0
  fl_chart: ^0.68.0 # for beautiful charts
  google_fonts: ^6.2.1
  sqflite: ^2.3.2
  shared_preferences: 2.5.5

flutter:
  uses-material-design: true